#!/usr/bin/env bash
set -e

ROOT=$(cd "$(dirname "$0")" && pwd)
source "$ROOT/config.sh"

if [[ -z "$VERSION" ]]; then
  echo "VERSION not set in config.sh"
  exit 1
fi

OUT=dist/env-init.sh
mkdir -p dist

append_file() {
  local file="$1"

  echo "### ===== BEGIN $file ====="
  sed '/^#!/d' "$file"
  echo
  echo "### ===== END $file ====="
  echo
}

{
  echo '#!/usr/bin/env bash'
  echo "# Generated by build.sh"
  echo "# Version: $VERSION"
  echo "# Build time: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo

  append_file "config.sh"

  for f in lib/*.sh; do
    append_file "$f"
  done

  for f in modules/*.sh; do
    append_file "$f"
  done

  append_file "bootstrap.sh"

} > "$OUT"

chmod +x "$OUT"

sha256sum "$OUT" > "$OUT.sha256"

echo "Built env-init.sh version $VERSION"